### ISSUE TITLE
RMNeXt  原理？

### ISSUE THREAD

**Issue by lrfighting** [fxmeng/RMNet#10]
作者您好，我是个小白，很幸运看到了您的源码，想请问您的RMNeXt的原理是什么？我看其不像也repvgg，但使用了repblock和rmblock，可否进行告知呢？

**Comment by fxmeng** [comment]
RMNext是把类似ResNext的模型变为VGG

**Comment by lrfighting** [comment]
> RMNext是把类似ResNext的模型变为VGG
1.该文件 第171行的  layer0  是否应为stage0
2.我使用该模型，发现参数比resnet18 减少了很多，但是速度好像并没有变快，反而变慢了

**Comment by lrfighting** [comment]
> RMNext是把类似ResNext的模型变为VGG

1.该文件 第171行的 layer0 是否应为stage0
2.我使用该模型，发现参数比resnet18 减少了很多，但是速度好像并没有变快，反而变慢了

**Comment by fxmeng** [comment]
这个模型在原文中是用来对标ResNet34的, 另外建议能够结合剪枝等进一步的操作，从而最大化直筒型网络的优势，否则直接用这个模型，收益并不大。如果希望简单的使用准确率和速度表现比较好的模型，建议使用rmrepvgg.py里面的模型。
![16377590471084](https://user-images.githubusercontent.com/60565778/143243885-cdc87cc6-2bbc-4f17-9bd3-facce8150a01.png)

**Comment by lrfighting** [comment]
> 这个模型在原文中是用来对标ResNet34的, 另外建议能够结合剪枝等进一步的操作，从而最大化直筒型网络的优势，否则直接用这个模型，收益并不大。如果希望简单的使用准确率和速度表现比较好的模型，建议使用rmrepvgg.py里面的模型。 ![16377590471084](https://user-images.githubusercontent.com/60565778/143243885-cdc87cc6-2bbc-4f17-9bd3-facce8150a01.png)

好的，那请问该文件里面的repvgg21（rmrepvgg）  是对标于resnet18吗？其中repvgg A0 和这有什么区别呢？

**Comment by fxmeng** [comment]
rmrepvgg和repvgg的不同在于训练模型的残差连接是会跨越非线性层的，推理时的结构是一样的，优点就是随着深度增加准确率还能保持不错。非要对标resnet18的话，可以手动调节一下每一个stage的数量。
