### ISSUE TITLE
RM operation on SEBlock?

### ISSUE THREAD

**Issue by ttjjmm** [fxmeng/RMNet#11]
I do not understand the principle of RM operation on SEBlock, why you concat the original input feature map with input feature plus SE output? just for plain network structure when deploying? Please explain my puzzle thx !!

**Comment by fxmeng** [comment]
RM Operation can remove residual connection across the no-linear layer, besides ReLU mentioned in the original paper, we try to remove residual connection across the SEBlock too. For this purpose, additional channels are needed for reserving the input feature map, thus we concat the original input feature map with input feature plus SE output.

**Comment by ttjjmm** [comment]
yeah, I understand, thank you for your reply!
