### ISSUE TITLE
AttributeError: 'RMNeXt' object has no attribute 'layer0'

### ISSUE THREAD

**Issue by wolfworld6** [fxmeng/RMNet#15]
when I use the code to train the AE rmnext41_64x5_g16,i got this error, why? how do I solve it?

**Comment by fxmeng** [comment]
Thanks for your question,
I have changed the stage0 in lines 146&148 to layer0:
https://github.com/fxmeng/RMNet/blob/2b6175db0bf24f783b77ca0736c490f53e3097e3/models/rmnext.py#L146

**Comment by wolfworld6** [comment]
> stage0

thx very much , I know!
