### ISSUE TITLE
For MobileNetV3

### ISSUE THREAD

**Issue by qdd1234** [fxmeng/RMNet#6]
Hi, thanks for your wonderful work! In your paper, RM model can improve the performance of MobileNetV2, but your work do not implement RM model on MobileNetV3. Why did you choose MobileNetV2 instead of MobileNetV3? MobileNetV3 is better than MobileNetV2. Moreover, I want to ask if I want to apply RM model to MobileNetV3, the implementation of RM in MobileNetV3 is similar to RM model in MobilNetV2？ Thanks！

**Comment by fxmeng** [comment]
RM Operation can equivalent remove the residual connection from MobileNetV2.
Though better than MobileNetV2, there are SE blocks in MobileNetV3, which can't be removed by RM Operation.
One can design or search a plain MobileNet with SE module.
