### ISSUE TITLE
request about the default and pretrained mobilenetV2 model

### ISSUE THREAD

**Issue by mwsunshine** [fxmeng/RMNet#7]
Hi, 
   First of all, thank you for your insightful work! 
   I want to use your work to speed up my own network with the backbone of mobilenetV2. My question is that in your train.py file, the default model is RepVGG-A0, is there a default model for mobilenetV2? Furthermore, could you please provide your pretrained mobilenetV2 as well?
  Many thanks in advance!

**Comment by fxmeng** [comment]
Previously code only realize and conduct experiments on the CIFAR.  Now a new update version is available and can directly convert a PyTorch version MobileNetV2 to a plain model:
https://github.com/fxmeng/RMNet/blob/d8d1eea86e1ad7a387c908567f9bf3fddbc0ecb0/models/rmobilenet.py#L267
And carefully modulating the training structure will gain benefit when converting it to a plain model, e.g.:
https://github.com/fxmeng/RMNet/blob/b8a9848f954608a41c93ab6268ce63c14d4d2b28/models/rmobilenet.py#L229
