### ISSUE TITLE
rmnet26

### ISSUE THREAD

**Issue by lrfighting** [fxmeng/RMNet#8]
请问  没有提供rmnet26的源码吗 对应于resnet18和34

**Comment by fxmeng** [comment]
根据文章中的描述：’RMNet 26×3 32 have [2, 2, 2, 2] RMBlocks for each stage‘，只需在文件：
https://github.com/fxmeng/RMNet/blob/c4aada8cb6e47a39c04e8ec26e96e19a9972d83a/models/rmnext.py 中添加：
def rmnext26_64x3_g32(num_classes=1000):
  return RMNeXt([2, 2, 2, 2], num_classes=num_classes, base_wide=64, expand_ratio=3, cpg=32)

**Comment by lrfighting** [comment]
> 根据文章中的描述：’RMNet 26×3 32 have [2, 2, 2, 2] RMBlocks for each stage‘，只需在文件： https://github.com/fxmeng/RMNet/blob/c4aada8cb6e47a39c04e8ec26e96e19a9972d83a/models/rmnext.py 中添加： def rmnext26_64x3_g32(num_classes=1000): return RMNeXt([2, 2, 2, 2], num_classes=num_classes, base_wide=64, expand_ratio=3, cpg=32)

好的，感谢作者回复，这同样适用于resnet18吗？若使用resnet18内部还需要修改吗

**Comment by lrfighting** [comment]
> 根据文章中的描述：’RMNet 26×3 32 have [2, 2, 2, 2] RMBlocks for each stage‘，只需在文件： https://github.com/fxmeng/RMNet/blob/c4aada8cb6e47a39c04e8ec26e96e19a9972d83a/models/rmnext.py 中添加： def rmnext26_64x3_g32(num_classes=1000): return RMNeXt([2, 2, 2, 2], num_classes=num_classes, base_wide=64, expand_ratio=3, cpg=32)

好的，感谢作者回复！

**Comment by lrfighting** [comment]
> 根据文章中的描述：’RMNet 26×3 32 have [2, 2, 2, 2] RMBlocks for each stage‘，只需在文件： https://github.com/fxmeng/RMNet/blob/c4aada8cb6e47a39c04e8ec26e96e19a9972d83a/models/rmnext.py 中添加： def rmnext26_64x3_g32(num_classes=1000): return RMNeXt([2, 2, 2, 2], num_classes=num_classes, base_wide=64, expand_ratio=3, cpg=32)

作者您好，您所提供的rmnext.py 里面涉及到了repvgg，请问哪个文件里面是基础版的， 只涉及对resnet取消残差连接操作的呢？

**Comment by fxmeng** [comment]
https://github.com/fxmeng/RMNet/blob/c4aada8cb6e47a39c04e8ec26e96e19a9972d83a/models/resnet2vgg.py

**Comment by lrfighting** [comment]
> https://github.com/fxmeng/RMNet/blob/c4aada8cb6e47a39c04e8ec26e96e19a9972d83a/models/resnet2vgg.py

感谢作者，谢谢~
