### ISSUE TITLE
about speed

### ISSUE THREAD

**Issue by datuizhuang** [fxmeng/RMNet#9]
您好，请问在不剪枝的情况下，通道数翻倍了。显存和推理速度不会明显恶化么？

**Comment by fxmeng** [comment]
是的，如果只是简单的把resnet变成直筒型网络并没有什么收益，所以需要结合文中指出的几种方法来最大化直筒型网络的收益，减少增加的代价。

**Comment by datuizhuang** [comment]
我自己复现了一版，单纯转换模型没有额外操作的话，精度一致，参数量变成了10倍（13,966,666 --> 148,197,194），得继续研究下剪枝了emmmm

**Comment by fxmeng** [comment]
resnet18吗？参数量变10倍不对呀，正常应该就2倍。建议仔细检查下代码，是否有哪里实现的不对。

**Comment by datuizhuang** [comment]
sorry搞错了，测试了一下，BacisBlock是正常的，BottleNeck的参数量变化很大，第二个卷积会膨胀很多。

**Comment by fxmeng** [comment]
嗯嗯，那就没问题了，Bottleneck输入宽中间窄，需要4倍通道做reserve，而且这四倍通道还需要是3*3卷积，所以会膨胀比较大。建议将Bottleneck改为‘’窄宽窄‘’形状，或者可以考虑利用一些压缩手段，使用更少的通道来保留输入特征，然后能比较好的还原回去。

**Comment by datuizhuang** [comment]
你好，我还有个问题。以BasicBlock举例，为了去掉residual，第一个conv的weight由[o, i, k, k] --> [i+o, i, k, k]，上半部分是个恒等变换，nn.init.dirac_(weight[:i])。但是到relu的时候，恒等变换的部分（也就是input）的元素有正有负，为什么简单使用了一个relu呢？按我的理解，应该对relu的输入切片，下部分做relu，上半部分不计算。
测了你的代码ResBlock，发现deploy之后的输出和forward的输出也确实不相等，想知道你这么做的原因；
按我自己的想法，我自己会对ReLU重新封装一下，但是在剪枝的时候非常麻烦，要考虑被剪掉channel是恒等变换部分还是常规部分，有点写不动。

**Comment by twmht** [comment]
@fxmeng 

看起來只有 RMRepVGG 能在不剪枝的情況下不傷害到速度?
